### PR TITLE
Add open tree links to pages in breadcrumb

### PR DESCRIPTION
**Pull request by adrianbj**
Not sure if you'd be happy adding this, but I find it quite useful for navigating back to the page tree in a highly nested site.

### CODE REVIEW

**Comment by adrianbj** [comment]
I guess one catch with this is that users might expect these new links to open the page for editing, rather than the tree with this parent open. Not sure whether this is ok and something they'll get the hang of or not - maybe they might need a little direction to let them know to go to the preceding `>` to click on the page to edit?

**Comment by Toutouwai** [comment]
I'm happy to merge this (will do it tomorrow), and having the last item be a link makes sense because that's a new breadcrumb item that the module is adding and so it should be like the others.

But regarding the other breadcrumb items, in your pull request those links would be unchanged from the core apart from the link for the parent page item, which in the core doesn't include include an `open` parameter. Do you understand the reasoning behind that item being different in the core? It has puzzled me from time to time. If there isn't a good reason for it not to have the `open` parameter then maybe this should be raised in the core issues repo rather than only "fixed" in this module?

**Comment by adrianbj** [comment]
> Do you understand the reasoning behind that item being different in the core? It has puzzled me from time to time. If there isn't a good reason for it not to have the open parameter then maybe this should be raised in the core issues repo rather than only "fixed" in this module?

I really don't know - I thought I had brought it up before, but I can't find it at the moment. I understand your logic in getting it fixed in the core though, but I am guessing it won't likely reach the top of Ryan's priorities anytime soon.

**Comment by Toutouwai** [comment]
> I thought I had brought it up before, but I can't find it at the moment

I looked through the core issues and it's been raised a number of times:
https://github.com/processwire/processwire-issues/issues/22
https://github.com/processwire/processwire-issues/issues/32
https://github.com/processwire/processwire-issues/issues/212

It seems that Ryan's on the fence on this one. It was a deliberately introduced feature but he also acknowledges it can be problematic for some.

Having a link without the `open` parameter is useful because it's currently the only way to go back to the tree and have the pagination remembered. But seeing as that type of link is also available via Pages and Pages > Tree I think it will be fine to remove it from the breadcrumb for the sake of consistency.

**Comment by adrianbj** [comment]
> But seeing as that type of link is also available via Pages and Pages > Tree I think it will be fine to remove it from the breadcrumb for the sake of consistency.

Sounds good to me - thanks for digging those up!

**Pull request merged**
